/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import Employee_Data.Employee;
import Employee_Data.EmployeeDirectory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Veenadharini25
 */
public class UpdateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UpdateJPanel
     */
    EmployeeDirectory directory;
    
    public UpdateJPanel(EmployeeDirectory directory) {
        initComponents();
        this.directory = directory;
        populateEmpTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUpdateEmp = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmployee = new javax.swing.JTable();

        lblUpdateEmp.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lblUpdateEmp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUpdateEmp.setText("Update Employee");
        lblUpdateEmp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tblEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Employee ID", "Age", "Gender", "Start Date", "Level", "Team Info", "Position Title", "Contact no.", "Email", "Photo"
            }
        ));
        tblEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEmployeeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEmployee);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(lblUpdateEmp, javax.swing.GroupLayout.DEFAULT_SIZE, 876, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblUpdateEmp)
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmployeeMouseClicked
        // TODO add your handling code here:
        /*DefaultTableModel tblModel = (DefaultTableModel)tblEmployee.getModel();

        String tblName = tblModel.getValueAt(tblEmployee.getSelectedRow(),0).toString();
        String tblEmpId =tblModel.getValueAt(tblEmployee.getSelectedRow(),1).toString();

        String name = txtName.getText();
        long employee_id = Long.parseLong(txtEmployeeID.getText());
        int age = Integer.parseInt(txtAge.getText());
        String gender = txtGender.getText();
        String start_date = txtStartDate.getText();
        int level = Integer.parseInt(txtLevel.getText());
        String team_info = txtTeamInfo.getText();
        String pos_title = txtPositionTitle.getText();
        long cell_no = Long.parseLong(txtContactNo.getText());
        String email = txtEmail.getText();
        txtName.setText(tblName);
        txtEmployeeID.setText(tblEmpId); */

    }//GEN-LAST:event_tblEmployeeMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblUpdateEmp;
    private javax.swing.JTable tblEmployee;
    // End of variables declaration//GEN-END:variables

    private void populateEmpTable() {
       
        
        DefaultTableModel model = (DefaultTableModel)tblEmployee.getModel();
        model.setRowCount(0);
        
        for (Employee e: directory.getDirectory()){
            
            Object[] row = new Object[11];
            row[0] = e;
            row[1] = e.getEmployee_id();
            row[2] = e.getAge();
            row[3] = e.getGender();
            row[4] = e.getStart_date();
            row[5] = e.getLevel();
            row[6] = e.getTeam_info();
            row[7] = e.getPosition_title();
            row[8] = e.getCell_no();
            row[9] = e.getEmail_add();
            row[10] = e.getPhoto();
            
            model.addRow(row);
        }
    }
}
